<?php
/*
 * If you would like your viewers to be able to subscribe to your playlist with RSS use getRSS() method as seen below.
 * The XML code generated by the getRSS() method is what your viewers will need to link to with their RSS readers.
 */

require 'ytpl_php.php';
header('Content-Type: application/xml; charset=UTF-8');


$playlist = new YoutubePlayList($playlistID = "nqdTIS_B64I7zbB_tPgvHiFTnmIqpT0u", $cacheAge = 1);

/*
 * @playListUR
 * Set playListURL to the Full URL - including http(s):// - where the playlist will reside on your website.
 * If unset or left null, the default playListURL is the actual playlist URL on Youtube.

 * @showNumVideos
 * The number of videos that will show up in the RSS feed, default is 10
 */
echo $playlist->getRSS(array("showNumVideos" => 25, "playListURL" => null));
